import type { NextPage } from "next";
import Head from "next/head";
import Feature from "../components/landingPage/Feature";
import Footer from "../components/landingPage/Footer";
import Hero from "../components/landingPage/Hero";
import Navbar from "../components/landingPage/Navbar";

const Home: NextPage = () => {
  return (
    <div className=" bg-cashfer-light-purple">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Navbar />
        <Hero />
        <Feature />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
