import React, { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import LoginIllustration from "../components/loginPage/LoginIllustration";
import LoginField from "../components/loginPage/LoginField";
import CancelToHome from "../components/general/CancelToHome";
import { userService } from "../Services/userService";


const login = () => {
  const router = useRouter();

  useEffect(() => {
    // redirect to home if already logged in
    if (userService.userValue) {
      router.push("/dashboard");
    }
  });

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
      </Head>

      <div className="lg:flex justify-between lg:items-start">
        <div className="hidden lg:block lg:w-4/12">
          <LoginIllustration />
        </div>
        <div className="lg:w-3/12 mx-auto">
          <CancelToHome />
          <LoginField />
        </div>
      </div>
    </div>
  );
};

export default login;
