import React from 'react'
import RegisterIllustration from '../components/registerPage/RegisterIllustration'
import Head from "next/head";
import RegisterFields from '../components/registerPage/RegisterFields';

const register = () => {
    return (
      <div>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/cashfer favicon.svg" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap"
            rel="stylesheet"
          />
        </Head>
        <div className="lg:flex lg:items-start">
          <div className="hidden lg:block lg:w-4/12">
            <RegisterIllustration />
          </div>
          <div className="lg:w-6/12 mx-auto">
           <RegisterFields />
          </div>
        </div>
      </div>
    );
}

export default register
