import React, { useContext, useEffect, useState } from "react";
import RegisterIllustration from "../components/registerPage/RegisterIllustration";
import Head from "next/head";
import RegisterFields from "../components/registerPage/RegisterFields";
import { currencyService } from "../Services/currencyService";
import axios from "axios";
import Image from "next/image";
import Loader from "../components/general/Loader";

const register = () => {
  const [currencies, setcurrencies] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setIsLoading(true);
    const config = {
      headers: {
        "Content-Type": "application/json",
      },
    };
    async function getCurrencies() {
      try {
        const response = await axios.get(
          "https://localhost:44362/api/Currency/GetAllCurrencies",
          config
        );
       
         const currencies = await response.data.data;
         setcurrencies(currencies);
         setIsLoading(false);
      } catch (error) {
        console.log(error);
      }
    }
     getCurrencies();
       return () => (setIsLoading(false));
  }, []);

  console.log("====================================");
  console.log(currencies);
  console.log("====================================");
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
      </Head>
      {!isLoading ? (
        <div className="lg:flex lg:items-start">
          <div className="hidden lg:block lg:w-4/12">
            <RegisterIllustration />
          </div>
          <div className="lg:w-6/12 mx-auto">
            <RegisterFields data={currencies} />
          </div>
        </div>
      ) : (
      <Loader />
      )}
    </div>
  );
};

export default register;
