import React from "react";
import Head from "next/head";
import WalletBalance from "../../components/walletPage/WalletBalance";
import Layout from "../../components/dashboardPage/Layout";
import SendRecieveMoney from "../../components/walletPage/SendRecieveMoney";
import TableList from "../../components/general/TableList";
import { useTheme } from "next-themes";

const Index = () => {
  const { theme, setTheme } = useTheme();

  const Toggle = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
      </Head>
      <div className="dark:bg-gray-900 bg-cashfer-light-purple">
        <Layout toggle={Toggle}>
          <div>
            <SendRecieveMoney />
            <WalletBalance />
            <div className="">
              <TableList />
            </div>
          </div>
        </Layout>
      </div>
    </div>
  );
};
export default Index;
