import React, { useEffect, useState, useContext } from "react";
import Head from "next/head";
import WalletBalance from "../../components/walletPage/WalletBalance";
import SendRecieveMoney from "../../components/walletPage/SendRecieveMoney";
import TableList from "../../components/general/TableList";
import { userService } from "../../Services/userService";
import { setAuthToken } from "../../Helpers/setAuthToken";
import { walletService } from "../../Services/walletService";
import { transactionService } from "../../Services/transactionService";
import CreateTransactionState from "../../Context/transaction/TransactionState";
import CreateWalletState from "../../Context/wallet/WalletState";
import TestDarkModeToggle from "../../components/general/TestDarkModeToggle";

const Index = () => {
  const [wallets, setwallets] = useState({});
  const [transactionResponse, setTransactionResponse] = useState([]);
 
  console.log("@@@@@@@@@@@@@@@@@@@@@", transactionResponse);

  useEffect(() => {
    setAuthToken(userService.userValue);
  }, []);

  useEffect(() => {
    let abortController = new AbortController();

    const getWallet = () => {
      walletService
        .getMyWallet()
        .then((data) => {
          console.log("*********************", data);
          // get return url from query parameters or default to '/'
          setwallets(data)
          console.log(data);
        })
        .catch(() => {
          //alertService.error("session expired, Log In again")
          alert("session expired, Login to continue");
          userService.logout();
        });
    };
    getWallet();
    return () => {
      abortController.abort();
    };
  }, []);


  return (
    <CreateTransactionState>
      <CreateWalletState>
        <div>
          <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/cashfer favicon.svg" />
          </Head>
          <div className="dark:bg-gray-900 bg-cashfer-light-purple">
            <div>
              <SendRecieveMoney />
              <WalletBalance wallets={wallets} />
           
              {/* <div>{walletId}</div> */}
              <div className="">
                <TableList />
              </div>
            </div>
          </div>
        </div>
      </CreateWalletState>
    </CreateTransactionState>
  );
};

// export async function getServerSideProps() {
//   const res = await fetch (
//     "https://localhost:44362/api/Currency/GetAllCurrencies"
//   ).then((datas) => {
//     const data = datas.json();
//   });

//   console.log("^^^^^^^^^^^^^^^^^^^^^^^^^");
//   return {
//     props: { data },
//   };
// }

export default Index;
