import * as React from "react";
import Head from "next/head";
import Tabs from "../../components/general/Tabs";
import Layout from "../../components/dashboardPage/Layout";
import ProfileDetails from "../../components/profilePage/ProfileDetails";
import FollowSideBar from "../../components/profilePage/FollowSideBar";

interface IProfileProps {}

const Profile: React.FunctionComponent<IProfileProps> = (props): any => {
  return (
    <div>
      <Head>
        <title>Transaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="bg-cashfer-light-purple">
        <Layout>
          <div className="flex justify-between">
            <div className="border flex-1">
              {" "}
              <ProfileDetails />
              <div>
                <Tabs>
                  <div label="Portfolio">
                    this is <i>portfolio</i> tab
                  </div>
                  <div label="About">
                    this is <i>about</i> tab
                  </div>
                </Tabs>
              </div>
              <div>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem
                dignissimos quae cum sed debitis omnis, beatae voluptatem cumque
                fugiat totam mollitia numquam est assumenda quidem ut
                necessitatibus harum sit. Suscipit?
              </div>
            </div>
            <div className="hidden lg:block w-80 bg-cashfer-medium-purple">
              {" "}
              <FollowSideBar />
            </div>
          </div>
        </Layout>
      </div>
    </div>
  );
};

export default Profile;
