import React from 'react'
import Head from "next/head";
import Layout from "../../components/dashboardPage/Layout";
import { useTheme } from "next-themes";
import FollowList from '../../components/general/FollowList'

const userSuggestions = () => {
     const { theme, setTheme } = useTheme();

  const Toggle = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  }

    return (
      <div>
        <Head>
          <title>Suggestions</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/cashfer favicon.svg" />
        </Head>
        <div className="bg-cashfer-light-purple dark:bg-gray-900">
          <Layout toggle={Toggle}>
            <div>
              <FollowList />
            </div>
          </Layout>
        </div>
      </div>
    );
}

export default userSuggestions
