import React from "react";
import Head from "next/head";
import FollowList from "../../components/general/FollowList";

const userSuggestions = () => {
  return (
    <div>
      <Head>
        <title>Suggestions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
      </Head>
      <div className="bg-cashfer-light-purple dark:bg-gray-900">
        <div>
          <FollowList />
        </div>
      </div>
    </div>
  );
};

export default userSuggestions;
