import React from 'react'
import Head from "next/head";
import Tabs from "../../components/general/Tabs";
import Layout from "../../components/dashboardPage/Layout";
import Transaction from '../../components/transactionPage/Transcations';


const transactions = () => {
     return (
       <div>
         <Head>
           <title>Transaction</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/cashfer favicon.svg" />
           <link
             href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;900&display=swap"
             rel="stylesheet"
           />
         </Head>
         <div className="bg-cashfer-light-purple">
           <Layout>
             <div>
               <Transaction />
             </div>
           </Layout>
         </div>
       </div>
     );
}

export default transactions
