import React from 'react'
import Head from "next/head";
import Layout from "../../components/dashboardPage/Layout";
import Transaction from '../../components/transactionPage/Transcations';
import { useTheme } from "next-themes";
import TableList from '../../components/general/TableList';


const transactions = () => {

  const { theme, setTheme } = useTheme();

  const Toggle = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };

     return (
       <div>
         <Head>
           <title>Transaction</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/cashfer favicon.svg" />
         </Head>
         <div className="bg-cashfer-light-purple dark:bg-gray-900">
           <Layout toggle={Toggle}>
             <div>
               <Transaction />
             </div>
           </Layout>
         </div>
       </div>
     );
}

export default transactions
