import React, { useEffect } from "react";
import Head from "next/head";
import Transaction from "../../components/transactionPage/Transcations";
import TableList from "../../components/general/TableList";
import Loader from "../../components/general/Loader";
import CreateTransactionState from "../../Context/transaction/TransactionState";

const transactions = () => {

  const [isLoading, setisLoading] = React.useState(true);

  useEffect(() => {
    setTimeout(() => {
      setisLoading(false);
    }, 2000);
    () => {
      setisLoading(true);
    };
  }, []);

  return (
    <div>
      <div>
        <CreateTransactionState>
          {" "}
          <Head>
            <title>Transaction</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/cashfer favicon.svg" />
          </Head>
          <div className="bg-cashfer-light-purple dark:bg-gray-900">
          
              <div>
                {isLoading == true ? (
                  <div>
                    <Loader />
                  </div>
                ) : (
                  <Transaction />
                )}
              </div>
         
          </div>
        </CreateTransactionState>
      </div>
    </div>
  );
};

export default transactions;
