
import Head from "next/head";
import React from "react";
import EditFields from "../../../components/editProfilePage/EditFields";


const edit = () => {
  
  return (
    <div>
      <Head>
        <title>Edit Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cashfer favicon.svg" />
      </Head>

      <div className="dark:bg-gray-900 bg-cashfer-light-purple">
     
          <div className="flex justify-between">
            <div className="flex-1">
              {" "}
             <EditFields/>
        
            </div>
          </div>
      
      </div>
    </div>
  );
};

export default edit;
